{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNPTHXZc0fKBVHTwiuU+UIF",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/CHARAN-MAJJI/HelloApp/blob/main/Elab_DSA.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**ARRAYS**"
      ],
      "metadata": {
        "id": "TwcE233L3DeS"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 1**"
      ],
      "metadata": {
        "id": "vgGs6Zcn3PB3"
      }
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "tcmkH8m92Ad4"
      },
      "outputs": [],
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "#define MAXN 100\n",
        "\n",
        "int s[MAXN];\n",
        "\n",
        "#define read(x) scanf(\"%d\", &(x))\n",
        "\n",
        "void sol()\n",
        "{\n",
        "    int n;\n",
        "    read(n);\n",
        "\n",
        "    for (int i = 0; i < n; i++)\n",
        "    {\n",
        "        read(s[i]);\n",
        "    }\n",
        "\n",
        "    // Sort the array\n",
        "    for (int i = 0; i < n - 1; i++)\n",
        "    {\n",
        "        for (int j = i + 1; j < n; j++)\n",
        "        {\n",
        "            if (s[i] > s[j])\n",
        "            {\n",
        "                int temp = s[i];\n",
        "                s[i] = s[j];\n",
        "                s[j] = temp;\n",
        "            }\n",
        "        }\n",
        "    }\n",
        "\n",
        "    int treats = 1;\n",
        "    int total = 0;\n",
        "\n",
        "    for (int i = 0; i < n; i++)\n",
        "    {\n",
        "        if (i > 0 && s[i] != s[i - 1])\n",
        "        {\n",
        "            treats++;\n",
        "        }\n",
        "\n",
        "        total += treats;\n",
        "    }\n",
        "\n",
        "    printf(\"%d\\n\", total);\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int T;\n",
        "    read(T);\n",
        "\n",
        "    while (T--)\n",
        "    {\n",
        "        sol();\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 2**"
      ],
      "metadata": {
        "id": "91Jz9JEp3eo4"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int p, q;\n",
        "    scanf(\"%d %d\", &p, &q);\n",
        "\n",
        "    char a[p][q];\n",
        "\n",
        "    int top = 0;\n",
        "    int bottom = p - 1;\n",
        "    int left = 0;\n",
        "    int right = q - 1;\n",
        "\n",
        "    char ch = 'Y';\n",
        "\n",
        "    while(top<=bottom && right>=left)\n",
        "    {\n",
        "        for(int j = left; j <= right; j++)\n",
        "            a[top][j] = ch;\n",
        "\n",
        "        for(int i = top; i <= bottom; i++)\n",
        "            a[i][right] = ch;\n",
        "\n",
        "        if(top < bottom)\n",
        "        {\n",
        "            for(int j = right; j >= left; j--)\n",
        "                a[bottom][j] = ch;\n",
        "        }\n",
        "\n",
        "        if(left < right)\n",
        "        {\n",
        "            for(int i = bottom; i >= top; i--)\n",
        "                a[i][left] = ch;\n",
        "        }\n",
        "\n",
        "        top++;\n",
        "        bottom--;\n",
        "        left++;\n",
        "        right--;\n",
        "\n",
        "        if(ch == 'Y')\n",
        "            ch = '0';\n",
        "        else\n",
        "            ch = 'Y';\n",
        "    }\n",
        "\n",
        "    for(int i = 0; i < p; i++)\n",
        "    {\n",
        "        for(int j = 0; j < q; j++)\n",
        "        {\n",
        "            printf(\"%c\", a[i][j]);\n",
        "\n",
        "            if(j < q - 1)\n",
        "                printf(\" \");\n",
        "        }\n",
        "\n",
        "        printf(\"\\n\");\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "7zWo9J4g2Vdx"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 3**"
      ],
      "metadata": {
        "id": "LE0jDy314Q90"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int g[105][105];\n",
        "\n",
        "void solve()\n",
        "{\n",
        "    int n;\n",
        "    scanf(\"%d\", &n);\n",
        "\n",
        "    int trace = 0;\n",
        "    int rCount = 0;\n",
        "    int cCount = 0;\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "    {\n",
        "        for(int j = 0;j < n;j++)\n",
        "        {\n",
        "            scanf(\"%d\", &g[i][j]);\n",
        "\n",
        "            if(i == j)\n",
        "                trace += g[i][j];\n",
        "        }\n",
        "    }\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "    {\n",
        "        int flag = 0;\n",
        "\n",
        "        for(int j = 0;j < n;j++)\n",
        "        {\n",
        "            for(int k = j + 1;k < n;k++)\n",
        "            {\n",
        "                if(g[i][j] == g[i][k])\n",
        "                {\n",
        "                    flag = 1;\n",
        "                    break;\n",
        "                }\n",
        "            }\n",
        "\n",
        "            if(flag)\n",
        "                break;\n",
        "        }\n",
        "\n",
        "        if(flag)\n",
        "            rCount++;\n",
        "    }\n",
        "\n",
        "    for(int j = 0;j < n;j++)\n",
        "    {\n",
        "        int flag = 0;\n",
        "\n",
        "        for(int i = 0;i < n;i++)\n",
        "        {\n",
        "            for(int k = i + 1;k < n;k++)\n",
        "            {\n",
        "                if(g[i][j] == g[k][j])\n",
        "                {\n",
        "                    flag = 1;\n",
        "                    break;\n",
        "                }\n",
        "            }\n",
        "\n",
        "            if(flag)\n",
        "                break;\n",
        "        }\n",
        "\n",
        "        if(flag)\n",
        "            cCount++;\n",
        "    }\n",
        "\n",
        "    printf(\"%d %d %d\\n\", trace, rCount, cCount);\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int T;\n",
        "    scanf(\"%d\", &T);\n",
        "\n",
        "    while(T--)\n",
        "        solve();\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "pl5-gZmi45xM"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 4**"
      ],
      "metadata": {
        "id": "DCTtevIZ3lS0"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n, a[100], count[1000] = {0};\n",
        "    int max = 0, ans = 0;\n",
        "\n",
        "    scanf(\"%d\", &n);\n",
        "\n",
        "    for (int i = 0; i < n; i++)\n",
        "        scanf(\"%d\", &a[i]);\n",
        "\n",
        "    for (int i = 0; i < n; i++)\n",
        "        count[a[i]]++;\n",
        "\n",
        "    for (int i = 0; i < n; i++)\n",
        "    {\n",
        "        if (count[a[i]] > max)\n",
        "        {\n",
        "            max = count[a[i]];\n",
        "            ans = a[i];\n",
        "        }\n",
        "    }\n",
        "\n",
        "    printf(\"%d\", ans);\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "fsxb6bj73uI9"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 5**"
      ],
      "metadata": {
        "id": "lL3qDJOgFekN"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n;\n",
        "    scanf(\"%d\",&n);\n",
        "\n",
        "    int arr[n];\n",
        "\n",
        "    for(int i=0;i<n;i++)\n",
        "        scanf(\"%d\",&arr[i]);\n",
        "\n",
        "    for(int i=0;i<n/2;i++)\n",
        "    {\n",
        "        int temp=arr[i];\n",
        "        arr[i]=arr[n-1-i];\n",
        "        arr[n-1-i]=temp;\n",
        "    }\n",
        "\n",
        "    for(int i=0;i<n;i++)\n",
        "        printf(\"%d \",arr[i]);\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "CPtRnJMbFhXf"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 06**"
      ],
      "metadata": {
        "id": "R5qPCNDH6Xwf"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "#include <math.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int q;\n",
        "    scanf(\"%d\", &q);\n",
        "\n",
        "    while(q--)\n",
        "    {\n",
        "        long long start, end;\n",
        "        scanf(\"%lld %lld\", &start, &end);\n",
        "\n",
        "        long long a = (long long)sqrt((double)end);\n",
        "        long long b = (long long)sqrt((double)(start - 1));\n",
        "\n",
        "        printf(\"%lld\\n\", a - b);\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "e1o8yJms6gFC"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 07**"
      ],
      "metadata": {
        "id": "7U6dVKg_7Noz"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n;\n",
        "\n",
        "    while(scanf(\"%d\", &n) == 1)\n",
        "    {\n",
        "        char buf[] = {[1000] = '\\0'};\n",
        "        int i = 0;\n",
        "\n",
        "        while(n>=10)\n",
        "        {\n",
        "            if(n >= 1000)\n",
        "            {\n",
        "                buf[i++]='R';\n",
        "                n -= 1000;\n",
        "            }\n",
        "            else if(n >= 900)\n",
        "            {\n",
        "                buf[i++]='B';\n",
        "                buf[i++]='R';\n",
        "                n -= 900;\n",
        "            }\n",
        "            else if(n >= 500)\n",
        "            {\n",
        "                buf[i++]='G';\n",
        "                n -= 500;\n",
        "            }\n",
        "            else if(n >= 400)\n",
        "            {\n",
        "                buf[i++]='B';\n",
        "                buf[i++]='G';\n",
        "                n -= 400;\n",
        "            }\n",
        "            else if(n >= 100)\n",
        "            {\n",
        "                buf[i++]='B';\n",
        "                n -= 100;\n",
        "            }\n",
        "            else if(n >= 90)\n",
        "            {\n",
        "                buf[i++]='Z';\n",
        "                buf[i++]='B';\n",
        "                n -= 90;\n",
        "            }\n",
        "            else if(n >= 50)\n",
        "            {\n",
        "                buf[i++]='P';\n",
        "                n -= 50;\n",
        "            }\n",
        "            else if(n >= 40)\n",
        "            {\n",
        "                buf[i++]='Z';\n",
        "                buf[i++]='P';\n",
        "                n -= 40;\n",
        "            }\n",
        "            else\n",
        "            {\n",
        "                buf[i++]='Z';\n",
        "                n -= 10;\n",
        "            }\n",
        "        }\n",
        "\n",
        "        while(n > 0)\n",
        "        {\n",
        "            if(n >= 9)\n",
        "            {\n",
        "                buf[i++]='B';\n",
        "                buf[i++]='K';\n",
        "                n -= 9;\n",
        "            }\n",
        "            else if(n >= 5)\n",
        "            {\n",
        "                buf[i++]='W';\n",
        "                n -= 5;\n",
        "            }\n",
        "            else if(n >= 4)\n",
        "            {\n",
        "                buf[i++]='B';\n",
        "                buf[i++]='W';\n",
        "                n -= 4;\n",
        "            }\n",
        "            else\n",
        "            {\n",
        "                buf[i++]='B';\n",
        "                n--;\n",
        "            }\n",
        "        }\n",
        "\n",
        "        printf(\"%s\\n\", buf);\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "tNbDIOI07RNs"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 08**"
      ],
      "metadata": {
        "id": "dlAotgCX8hES"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int rotLeft(int arr[],int n,int d)\n",
        "{\n",
        "    int temp[1000];\n",
        "\n",
        "    d = d % n;\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "        temp[i] = arr[(i + d) % n];\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "        arr[i] = temp[i];\n",
        "\n",
        "    return 0;\n",
        "}\n",
        "\n",
        "int rotRight(int arr[],int n,int d)\n",
        "{\n",
        "    int temp[1000];\n",
        "\n",
        "    d = d % n;\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "        temp[i] = arr[(i - d + n) % n];\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "        arr[i] = temp[i];\n",
        "\n",
        "    return 0;\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n,d;\n",
        "    char ch;\n",
        "    int arr[1000];\n",
        "\n",
        "    scanf(\"%d\",&n);\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "        scanf(\"%d\",&arr[i]);\n",
        "\n",
        "    scanf(\"%d\",&d);\n",
        "    scanf(\" %c\",&ch);\n",
        "\n",
        "    if(ch == 'L')\n",
        "        rotLeft(arr,n,d);\n",
        "    else\n",
        "        rotRight(arr,n,d);\n",
        "\n",
        "    for(int i = 0;i < n;i++)\n",
        "    {\n",
        "        if(i > 0)\n",
        "            printf(\" \");\n",
        "\n",
        "        printf(\"%d\",arr[i]);\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "Ts6h_VTc8nPf"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 09**"
      ],
      "metadata": {
        "id": "nZjzmsm7-Qt4"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int rows, i, j;\n",
        "    scanf(\"%d\", &rows);\n",
        "\n",
        "    for(i=1;i<=rows;i++)\n",
        "    {\n",
        "        for(j=1;j<=i;j++)\n",
        "        {\n",
        "            if(i==rows || j==1 || j==i)\n",
        "                printf(\"1 \");\n",
        "            else\n",
        "                printf(\"0 \");\n",
        "        }\n",
        "\n",
        "        printf(\"\\n\");\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "gUHf-V_x-VIZ"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 10**"
      ],
      "metadata": {
        "id": "SsIEsQ7a-WVU"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "#include <limits.h>\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n1,n2,i,j;\n",
        "    scanf(\"%d\",&n1);\n",
        "    int a[n1];\n",
        "    long long x[100];\n",
        "\n",
        "    for(i=0;i<n1;i++) scanf(\"%d\",&a[i]),x[i]=a[i];\n",
        "    x[n1]=LLONG_MAX/4;\n",
        "\n",
        "    scanf(\"%d\",&n2);\n",
        "    int b[n2],p[n2];\n",
        "    for(i=0;i<n2;i++) scanf(\"%d\",&b[i]),p[i]=0;\n",
        "\n",
        "    int k;\n",
        "    scanf(\"%d\",&k);\n",
        "\n",
        "    while(k--)\n",
        "    {\n",
        "        int c=0;\n",
        "        long long m=LLONG_MAX;\n",
        "\n",
        "        for(j=0;j<n2;j++)\n",
        "            if(x[p[j]]+b[j]<m)\n",
        "                m=x[p[j]]+b[j],c=j;\n",
        "\n",
        "        printf(\"(%d,%d) \",a[p[c]],b[c]);\n",
        "        p[c]++;\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "gotjS6kIE9St"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**LINKED LIST**"
      ],
      "metadata": {
        "id": "eKyGxC5URJ2i"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 1**"
      ],
      "metadata": {
        "id": "t0WJu3WzRWGl"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "\n",
        "struct n\n",
        "{\n",
        "    int data;\n",
        "    struct n *next;\n",
        "};\n",
        "\n",
        "struct n full[100], odd[100], even[100];\n",
        "struct n *fh, *ft, *oh, *ot, *eh, *et;\n",
        "int fc, oc, ec;\n",
        "\n",
        "void insert(int data)\n",
        "{\n",
        "    struct n *p;\n",
        "\n",
        "    p=&full[fc++];\n",
        "    p->data=data;\n",
        "    p->next=fh;\n",
        "    ft->next=p;\n",
        "    ft=p;\n",
        "\n",
        "    if(data%2)\n",
        "    {\n",
        "        p=&odd[oc++];\n",
        "        p->data=data;\n",
        "        p->next=oh;\n",
        "        ot->next=p;\n",
        "        ot=p;\n",
        "    }\n",
        "    else\n",
        "    {\n",
        "        p=&even[ec++];\n",
        "        p->data=data;\n",
        "        p->next=eh;\n",
        "        et->next=p;\n",
        "        et=p;\n",
        "    }\n",
        "}\n",
        "\n",
        "void display(struct n *h)\n",
        "{\n",
        "    struct n *p=h->next;\n",
        "\n",
        "    printf(\"[h]=>\");\n",
        "\n",
        "    do\n",
        "    {\n",
        "        printf(\"%d=>\",p->data);\n",
        "        p=p->next;\n",
        "    }\n",
        "    while(p!=h);\n",
        "\n",
        "    printf(\"[h]\\n\");\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n,i;\n",
        "\n",
        "    fh=&full[0];\n",
        "    oh=&odd[0];\n",
        "    eh=&even[0];\n",
        "\n",
        "    fh->next=fh;\n",
        "    oh->next=oh;\n",
        "    eh->next=eh;\n",
        "\n",
        "    ft=fh;\n",
        "    ot=oh;\n",
        "    et=eh;\n",
        "\n",
        "    fc=oc=ec=1;\n",
        "\n",
        "    scanf(\"%d\",&n);\n",
        "\n",
        "    for(i=1;i<=n;i++)\n",
        "        insert(i);\n",
        "\n",
        "    printf(\"Complete linked_list:\\n\");\n",
        "    display(fh);\n",
        "\n",
        "    printf(\"Odd:\\n\");\n",
        "    display(oh);\n",
        "\n",
        "    printf(\"Even:\\n\");\n",
        "    display(eh);\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "wMJHbMsWUco1"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 2**"
      ],
      "metadata": {
        "id": "tupH0wipUfM2"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include <stdio.h>\n",
        "#include <stdlib.h>\n",
        "\n",
        "struct Node\n",
        "{\n",
        "    int data;\n",
        "    struct Node *next;\n",
        "    struct Node *prev;\n",
        "};\n",
        "\n",
        "void insertStart(struct Node** head,int data)\n",
        "{\n",
        "    struct Node *newNode=malloc(sizeof(struct Node));\n",
        "\n",
        "    newNode->data=data;\n",
        "    newNode->prev=NULL;\n",
        "    newNode->next=*head;\n",
        "\n",
        "    if(*head!=NULL)\n",
        "        (*head)->prev=newNode;\n",
        "\n",
        "    *head=newNode;\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n,i,x;\n",
        "    struct Node *head=NULL;\n",
        "    struct Node *tail;\n",
        "\n",
        "    scanf(\"%d\",&n);\n",
        "\n",
        "    for(i=0;i<n;i++)\n",
        "    {\n",
        "        scanf(\"%d\",&x);\n",
        "        insertStart(&head,x);\n",
        "    }\n",
        "\n",
        "    for(tail=head;tail->next!=NULL;tail=tail->next);\n",
        "\n",
        "    for(struct Node *p=head;p!=NULL;p=p->next)\n",
        "        printf(\"%d \",p->data);\n",
        "\n",
        "    printf(\"\\n\");\n",
        "\n",
        "    for(struct Node *p=tail;p!=NULL;p=p->prev)\n",
        "        printf(\"%d \",p->data);\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "wzJYja3cUmij"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 3**"
      ],
      "metadata": {
        "id": "tg0O4hGtVRC6"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include<stdio.h>\n",
        "\n",
        "struct node{int data;struct node *next;};\n",
        "struct node a[100],*start,*p1=a;\n",
        "\n",
        "void insert(int data)\n",
        "{\n",
        "p1->data=data;p1->next=start;start=p1++;\n",
        "}\n",
        "\n",
        "void display()\n",
        "{\n",
        "p1=start;\n",
        "printf(\"Linked List:\");\n",
        "while(p1){printf(\"->%d\",p1->data);p1=p1->next;}\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "int n,i,x;scanf(\"%d\",&n);\n",
        "for(i=0;i<n;i++){scanf(\"%d\",&x);insert(x);}\n",
        "display();\n",
        "}"
      ],
      "metadata": {
        "id": "JsomXkI_VVcY"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 4**"
      ],
      "metadata": {
        "id": "uSlQURGkWwCU"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include<stdio.h>\n",
        "#include<stdlib.h>\n",
        "\n",
        "struct node\n",
        "{\n",
        "    int data;\n",
        "    struct node *next;\n",
        "};\n",
        "\n",
        "struct node *head=NULL,*tail=NULL;\n",
        "int D;\n",
        "\n",
        "void create()\n",
        "{\n",
        "    int n,i,x;\n",
        "    struct node *p;\n",
        "\n",
        "    scanf(\"%d\",&n);\n",
        "\n",
        "    for(i=0;i<n;i++)\n",
        "    {\n",
        "        scanf(\"%d\",&x);\n",
        "        p=malloc(sizeof(struct node));\n",
        "        p->data=x;\n",
        "        p->next=NULL;\n",
        "\n",
        "        if(head==NULL)\n",
        "            head=p;\n",
        "        else\n",
        "            tail->next=p;\n",
        "\n",
        "        tail=p;\n",
        "    }\n",
        "\n",
        "    scanf(\"%d\",&D);\n",
        "}\n",
        "\n",
        "void del()\n",
        "{\n",
        "    struct node dummy,*p2,*q;\n",
        "\n",
        "    dummy.next=head;\n",
        "    p2=&dummy;\n",
        "\n",
        "    while(p2->next)\n",
        "    {\n",
        "        q=p2->next;\n",
        "\n",
        "        if(q->data==D)\n",
        "            p2->next=q->next;\n",
        "        else\n",
        "            p2=p2->next;\n",
        "    }\n",
        "\n",
        "    head=dummy.next;\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    create();\n",
        "    del();\n",
        "\n",
        "    printf(\"Linked List:\");\n",
        "\n",
        "    while(head)\n",
        "    {\n",
        "        printf(\"->%d\",head->data);\n",
        "        head=head->next;\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "1KLFXoluZKw_"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 5**"
      ],
      "metadata": {
        "id": "4hDqdSSPZLkM"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#include<stdio.h>\n",
        "#include<stdlib.h>\n",
        "\n",
        "struct Node\n",
        "{\n",
        "    int data;\n",
        "    struct Node *next;\n",
        "};\n",
        "\n",
        "struct Node *next;\n",
        "\n",
        "void sortedInsert(struct Node** head_ref, struct Node* new_node)\n",
        "{\n",
        "    struct Node *p;\n",
        "\n",
        "    if(*head_ref==NULL)\n",
        "    {\n",
        "        new_node->next=new_node;\n",
        "        *head_ref=new_node;\n",
        "        return;\n",
        "    }\n",
        "\n",
        "    if(new_node->data<(*head_ref)->data)\n",
        "    {\n",
        "        p=*head_ref;\n",
        "\n",
        "        while(p->next!=*head_ref)\n",
        "            p=p->next;\n",
        "\n",
        "        new_node->next=*head_ref;\n",
        "        p->next=new_node;\n",
        "        *head_ref=new_node;\n",
        "        return;\n",
        "    }\n",
        "\n",
        "    p=*head_ref;\n",
        "\n",
        "    while(p->next!=*head_ref)\n",
        "    {\n",
        "        if(p->next->data>=new_node->data)\n",
        "            break;\n",
        "\n",
        "        p=p->next;\n",
        "    }\n",
        "\n",
        "    new_node->next=p->next;\n",
        "    p->next=new_node;\n",
        "}\n",
        "\n",
        "int main()\n",
        "{\n",
        "    int n,i,x;\n",
        "    struct Node *head=NULL,*p,*q;\n",
        "\n",
        "    scanf(\"%d\",&n);\n",
        "\n",
        "    for(i=0;i<n;i++)\n",
        "    {\n",
        "        scanf(\"%d\",&x);\n",
        "\n",
        "        q=malloc(sizeof(struct Node));\n",
        "        q->data=x;\n",
        "\n",
        "        sortedInsert(&head,q);\n",
        "    }\n",
        "\n",
        "    p=head;\n",
        "\n",
        "    for(i=0;i<n;i++)\n",
        "    {\n",
        "        printf(\"%d\",p->data);\n",
        "\n",
        "        if(i<n-1)\n",
        "            printf(\" \");\n",
        "\n",
        "        p=p->next;\n",
        "    }\n",
        "\n",
        "    return 0;\n",
        "}"
      ],
      "metadata": {
        "id": "KiFJvmePZUpd"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "**QUESTION 6**"
      ],
      "metadata": {
        "id": "G8DwSl54ayAE"
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "rnfCDYtCa8VY"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}